name: Docker Image CI

on:
  workflow_dispatch: # Allows manual trigger


jobs:
  build:
    # Only run if triggered by approval or manually AND PR is approved

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
