name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      target_env:
        description: "Select environment"
        required: true
        type: choice
        options:
          - dev
          - prod

jobs:
  build:
    runs-on: ubuntu-latest

    # Dynamically select the environment (GitHub Environments from repo settings)
    environment: ${{ github.event.inputs.target_env }}

    env:
      IMAGE_NAME: my-image-name

    steps:
      - uses: actions/checkout@v4

      - name: Print TEST_ENV
        run: echo "TEST_ENV is $TEST_ENV"
