name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      target_env:
        description: "Select environment"
        required: true
        type: choice
        options:
          - dev
          - prod

jobs:
  build:
    runs-on: ubuntu-latest

    environment: ${{ github.event.inputs.target_env }}

    env:
      IMAGE_NAME: my-image-name

    steps:
      - uses: actions/checkout@v4

      - name: Print selected environment
        run: echo "Selected env: ${{ github.event.inputs.target_env }}"

      - name: Print TEST_ENV
        run: echo "TEST_ENV is ${{ vars.TEST_ENV }}"
