name: Docker Image CI

on:
  workflow_dispatch: # manual trigger only

jobs:
  build:
    runs-on: ubuntu-latest

    # Use environment with required reviewers
    environment: dev

    env:
      IMAGE_NAME: my-image-name

    steps:
      - uses: actions/checkout@v4

      - name: Build the Docker image
        run: |
          docker build . \
            --file Dockerfile \
            --tag $IMAGE_NAME:${{ github.run_id }}
